"""Replace payroll/performance_reviews with holidays and employee_documents

Revision ID: 6de292014fe8
Revises: 7242f129d379
Create Date: 2026-07-03 11:37:49.095277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6de292014fe8'
down_revision = '7242f129d379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'name', name='uq_holiday_date_name')
    )
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holidays_date'), ['date'], unique=False)

    op.create_table('employee_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('ID_PROOF', 'OFFER_LETTER', 'RESUME', 'CERTIFICATE', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    with op.batch_alter_table('employee_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_documents_employee_id'), ['employee_id'], unique=False)

    with op.batch_alter_table('performance_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_reviews_employee_id'))

    op.drop_table('performance_reviews')
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_employee_id'))

    op.drop_table('payroll')
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('base_salary')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_salary', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))

    op.create_table('payroll',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('base_salary', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('deductions', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('net_pay', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('version_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('month >= 1 AND month <= 12', name=op.f('ck_payroll_month_valid')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('payroll_employee_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payroll_pkey')),
    sa.UniqueConstraint('employee_id', 'month', 'year', name=op.f('uq_payroll_employee_month_year'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payroll_employee_id'), ['employee_id'], unique=False)

    op.create_table('performance_reviews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reviewer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cycle', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('rating', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('ck_review_rating_range')),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('performance_reviews_employee_id_fkey')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('performance_reviews_reviewer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('performance_reviews_pkey'))
    )
    with op.batch_alter_table('performance_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_reviews_employee_id'), ['employee_id'], unique=False)

    with op.batch_alter_table('employee_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_documents_employee_id'))

    op.drop_table('employee_documents')
    with op.batch_alter_table('holidays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holidays_date'))

    op.drop_table('holidays')
    # ### end Alembic commands ###
