"""Add base_salary to employees for payroll simulation

Revision ID: 7242f129d379
Revises: b9553a73e1a1
Create Date: 2026-07-03 11:01:52.430602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7242f129d379'
down_revision = 'b9553a73e1a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_salary', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('base_salary')

    # ### end Alembic commands ###
